// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-vibes/CleanBright.tsx": () => import("../components/mockups/home-vibes/CleanBright.tsx"),
  "./components/mockups/home-vibes/DeepQuiet.tsx": () => import("../components/mockups/home-vibes/DeepQuiet.tsx"),
  "./components/mockups/home-vibes/HeroicLuminous.tsx": () => import("../components/mockups/home-vibes/HeroicLuminous.tsx"),
  "./components/mockups/home-vibes/PolishedConsistent.tsx": () => import("../components/mockups/home-vibes/PolishedConsistent.tsx"),
  "./components/mockups/home-vibes/WarmBold.tsx": () => import("../components/mockups/home-vibes/WarmBold.tsx")
};
